/* This is a script to seed all the book data into your database. 

    1. Before running this, please make sure the .env file contains:
    * Your SUPABASE SERVICE ROLE KEY
    * Your SUPABASE DOMAIN (PROJECT URL)

    You can find this information on your project dashboard.

    2. In Supabase SQL editor, run this SQL
        CREATE TABLE books (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            author TEXT NOT NULL,
            genre TEXT NOT NULL,
            year BIGINT NOT NULL,
            rating FLOAT NOT NULL,
            description TEXT NOT NULL,
            comments TEXT[]
        );

        Erase the above and run:

        ALTER TABLE books ENABLE ROW LEVEL SECURITY;

        Alternatively, you can create a table manually as well using Supabase GUI

        



    Once your .env file is populated with your credentials, run: node SeedBooks.js
*/

require('dotenv').config()

const { supabase } = require('./SupabaseClient')
const books = require('./books.json')

async function seedBooks() {
    const { error } = await supabase
    .from('books')
    .insert(books)
    if(error) {
        console.log(`There was an issue seeding the book data into your database. Details: ${error.details}, Message: ${error.message}, Hint:${error.hint}`)
    }
}

seedBooks()


